import type { Metadata } from "next";
import LegalPage, { type LegalBlock } from "../components/LegalPage";
import { SITE_URL } from "../lib/site";

export const metadata: Metadata = {
  title: "Terms & Conditions | C3 Properties",
  description:
    "Terms and conditions governing use of the C3 Properties LLC website and our short-term rental property management services in Melbourne, Florida.",
  alternates: { canonical: `${SITE_URL}/terms` },
};

const BLOCKS: LegalBlock[] = [
  { p: 'These Terms and Conditions ("Terms") govern your use of the C3 Properties LLC website and the property management services we provide. By using our website or engaging our services, you agree to be bound by these Terms.' },
  { h2: "1. Company Information" },
  { p: "C3 Properties LLC is a property management company operating in the State of Florida, specializing in premium short-term vacation rental management, dynamic pricing optimization, and guest experience services." },
  { list: ["Location: Melbourne, Florida", "Parent Company: Stay Starving Holdings LLC"] },
  { h2: "2. Website Use" },
  { h3: "2.1 Acceptance of Terms" },
  { p: "By accessing and using this website, you accept and agree to be bound by these Terms. If you do not agree, please do not use our website." },
  { h3: "2.2 Permitted Use" },
  { p: "You may use our website for lawful purposes only, including:" },
  { list: ["Reviewing our property management services and portfolio", "Submitting inquiries and property assessment requests", "Booking stays at our managed properties", "Contacting us for management consultations"] },
  { h3: "2.3 Prohibited Activities" },
  { p: "You agree not to:" },
  { list: ["Submit false or misleading information", "Attempt to interfere with website functionality", "Use the website for any unlawful purpose", "Scrape, copy, or reproduce website content without permission"] },
  { h2: "3. Property Management Services" },
  { h3: "3.1 Service Scope" },
  { p: "C3 Properties LLC provides comprehensive short-term rental management services, which may include:" },
  { list: ["Property listing creation and optimization across booking platforms", "Dynamic pricing and revenue management", "Guest communication and 24/7 support", "Professional cleaning coordination", "Property maintenance and smart home management", "Tax collection and remittance", "Monthly owner reporting and analytics"] },
  { h3: "3.2 Management Agreements" },
  { p: "All property management services are governed by a separate Property Management Agreement executed between C3 Properties LLC and the property owner. These Terms supplement but do not replace any executed management agreement." },
  { h3: "3.3 Non-Binding Inquiries" },
  { p: "Submitting an assessment request or inquiry through our website does not create a contractual obligation. All proposals are preliminary and subject to:" },
  { list: ["Property inspection and assessment", "Review of property condition, location, and market analysis", "Execution of a formal Property Management Agreement"] },
  { h2: "4. Guest Terms" },
  { h3: "4.1 Booking Terms" },
  { p: "Guests booking stays at C3 Properties-managed rentals are subject to:" },
  { list: ["The booking platform's terms of service (Airbnb, VRBO, etc.)", "House rules specific to each property", "Maximum occupancy limits as listed", "Check-in and check-out time requirements"] },
  { h3: "4.2 Property Rules" },
  { p: "All guests must comply with property-specific rules, which may include:" },
  { list: ["No smoking on property premises", "No unauthorized parties or events", "Quiet hours compliance", "Pet policies as specified per property", "Parking restrictions"] },
  { h3: "4.3 Damage and Liability" },
  { p: "Guests are responsible for any damage to the property or its contents during their stay beyond normal wear and tear. Damage claims may be processed through the booking platform's resolution center or billed directly." },
  { h2: "5. Florida Vacation Rental Compliance" },
  { note: "C3 Properties LLC operates in compliance with Florida Statutes Chapter 509 (Public Lodging Establishments), Brevard County short-term rental ordinances, and all applicable state and local regulations governing vacation rental properties." },
  { h3: "5.1 Licensing" },
  { p: "All managed properties maintain required licenses and registrations with the Florida Department of Business and Professional Regulation (DBPR) and applicable local authorities." },
  { h3: "5.2 Tax Collection" },
  { p: "C3 Properties LLC collects and remits all applicable taxes, including:" },
  { list: ["Florida State Sales Tax (6%)", "Brevard County Tourist Development Tax (5%)", "Any additional local surcharges as applicable"] },
  { h3: "5.3 Insurance" },
  { p: "Property owners are required to maintain appropriate insurance coverage, including short-term rental endorsements. C3 Properties LLC maintains its own general liability and professional liability coverage." },
  { h2: "6. Intellectual Property" },
  { p: "All content on this website, including text, graphics, logos, photographs, and images, is the property of C3 Properties LLC or its licensors and is protected by copyright and trademark laws. You may not reproduce, distribute, or create derivative works without our written permission." },
  { h2: "7. Limitation of Liability" },
  { h3: "7.1 Website Disclaimer" },
  { p: 'The information on this website is provided "as is" without warranties of any kind. Revenue projections, occupancy estimates, and market data are provided for informational purposes only and do not guarantee specific results.' },
  { h3: "7.2 Limitation of Damages" },
  { p: "To the maximum extent permitted by Florida law, C3 Properties LLC's liability for any claim arising from our services shall not exceed the management fees paid for the specific property in the twelve (12) months preceding the claim. We are not liable for indirect, incidental, special, or consequential damages." },
  { h3: "7.3 Force Majeure" },
  { p: "C3 Properties LLC is not liable for failure to perform obligations due to circumstances beyond reasonable control, including natural disasters, pandemics, government restrictions, utility failures, or acts of God." },
  { h2: "8. Dispute Resolution" },
  { h3: "8.1 Informal Resolution" },
  { p: "The parties agree to attempt to resolve any dispute informally before initiating formal proceedings. Either party may request a meeting to discuss the dispute in good faith." },
  { h3: "8.2 Mediation" },
  { p: "If informal resolution is unsuccessful, the parties agree to submit the dispute to mediation before a mutually agreed-upon mediator in Brevard County, Florida." },
  { h3: "8.3 Governing Law and Venue" },
  { p: "These Terms are governed by the laws of the State of Florida. Any legal action shall be brought in the courts of Brevard County, Florida, or the United States District Court for the Middle District of Florida." },
  { h3: "8.4 Attorney's Fees" },
  { p: "In any action to enforce these Terms, the prevailing party shall be entitled to recover reasonable attorney's fees and costs." },
  { h2: "9. Indemnification" },
  { p: "You agree to indemnify and hold harmless C3 Properties LLC, its officers, employees, and agents from any claims, damages, or expenses arising from your use of our website, your breach of these Terms, or your stay at a managed property." },
  { h2: "10. Privacy" },
  { p: "Your use of our website and services is also governed by our Privacy Policy, which is incorporated into these Terms by reference." },
  { h2: "11. Severability" },
  { p: "If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect." },
  { h2: "12. Modifications" },
  { p: "We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated effective date. Continued use of our website constitutes acceptance of modified Terms." },
  { h2: "13. Entire Agreement" },
  { p: "These Terms, together with our Privacy Policy and any executed Property Management Agreement, constitute the entire agreement between you and C3 Properties LLC regarding the subject matter herein." },
  { h2: "14. Contact Information" },
  { p: "For questions about these Terms, please contact us: C3 Properties LLC, Melbourne, Florida — info@c3properties.com — (407) 394-5358. A Stay Starving Holdings Company." },
  { note: "Legal Notice: These Terms and Conditions are designed to comply with Florida law and industry standards for short-term vacation rental management. For specific legal advice, please consult with a qualified Florida attorney." },
];

export default function TermsPage() {
  return <LegalPage title="Terms & Conditions" effectiveDate="March 5, 2026" blocks={BLOCKS} />;
}
